var express = require('express'),
    app = express(),
    path = require('path'),
    stylus = require('stylus'),
    port = process.argv[2],
    filesDir = process.argv[3];
    
    app.use(stylus.middleware(filesDir));
    app.use(express.static(filesDir));
    // app.use(express.static(path.join(filesDir || __dirname + 'public')));
        
    app.listen(port);
    
/*
Your solution should listen on the port supplied by process.argv[2] for
GET requests, one of which will be for main.css, which should be
automatically generated by your Stylus middleware. index.html and main.styl
 can be found in process.argv[3] (they are in the same directory).
*/    

/*
The main.styl file:

    p
      color red

The index.html file:

    <html>
      <head>
        <title>expressworks</title>
        <link rel="stylesheet" type="text/css" href="/main.css"/>
      </head>
      <body>
        <p>I am red!</p>
      </body>
    </html>
*/

/*
Offical solution

var express = require('express')
var app = express()

app.use(require('stylus').middleware(process.argv[3]));
app.use(express.static(process.argv[3]));


app.listen(process.argv[2])
*/





